services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookstore_api_test;" -U postgres
  - psql -c "CREATE USER bookstore_api WITH PASSWORD 'bookstore_api';" -U postgres
  - psql -c "ALTER USER bookstore_api CREATEDB;" -U postgres
  - psql -c "ALTER DATABASE bookstore_api_test OWNER TO bookstore_api;" -U postgres

language: ruby

rvm:
  - 2.6.2
